version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: mysecretpassword  # Пароль для PostgreSQL
      POSTGRES_USER: myuser                # Имя пользователя
      POSTGRES_DB: mydatabase              # Имя БД
    ports:
      - "5432:5432"                        # Проброс порта
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Папка для сохранения данных
      - ./parsing:/data  # Монтируем папку parsing из текущей директории в /data внутри контейнера
    restart: unless-stopped

volumes:
  postgres_data: